const list: any = [
  { countryCode: 'AF', name: 'Afghanistan', region: 'Asia' },
  { countryCode: 'AX', name: 'Åland Islands', region: 'Europe' },
  { countryCode: 'AL', name: 'Albania', region: 'Europe' },
  { countryCode: 'DZ', name: 'Algeria', region: 'Africa' },
  { countryCode: 'AS', name: 'American Samoa', region: 'Oceania' },
  { countryCode: 'AD', name: 'Andorra', region: 'Europe' },
  { countryCode: 'AO', name: 'Angola', region: 'Africa' },
  { countryCode: 'AI', name: 'Anguilla', region: 'Americas' },
  { countryCode: 'AQ', name: 'Antarctica', region: '' },
  { countryCode: 'AG', name: 'Antigua and Barbuda', region: 'Americas' },
  { countryCode: 'AR', name: 'Argentina', region: 'Americas' },
  { countryCode: 'AM', name: 'Armenia', region: 'Asia' },
  { countryCode: 'AW', name: 'Aruba', region: 'Americas' },
  { countryCode: 'AU', name: 'Australia', region: 'Oceania' },
  { countryCode: 'AT', name: 'Austria', region: 'Europe' },
  { countryCode: 'AZ', name: 'Azerbaijan', region: 'Asia' },
  { countryCode: 'BS', name: 'Bahamas', region: 'Americas' },
  { countryCode: 'BH', name: 'Bahrain', region: 'Asia' },
  { countryCode: 'BD', name: 'Bangladesh', region: 'Asia' },
  { countryCode: 'BB', name: 'Barbados', region: 'Americas' },
  { countryCode: 'BY', name: 'Belarus', region: 'Europe' },
  { countryCode: 'BE', name: 'Belgium', region: 'Europe' },
  { countryCode: 'BZ', name: 'Belize', region: 'Americas' },
  { countryCode: 'BJ', name: 'Benin', region: 'Africa' },
  { countryCode: 'BM', name: 'Bermuda', region: 'Americas' },
  { countryCode: 'BT', name: 'Bhutan', region: 'Asia' },
  { countryCode: 'BO', name: 'Bolivia (Plurinational State of)', region: 'Americas' },
  { countryCode: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', region: 'Americas' },
  { countryCode: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe' },
  { countryCode: 'BW', name: 'Botswana', region: 'Africa' },
  { countryCode: 'BV', name: 'Bouvet Island', region: 'Americas' },
  { countryCode: 'BR', name: 'Brazil', region: 'Americas' },
  { countryCode: 'IO', name: 'British Indian Ocean Territory', region: 'Africa' },
  { countryCode: 'BN', name: 'Brunei Darussalam', region: 'Asia' },
  { countryCode: 'BG', name: 'Bulgaria', region: 'Europe' },
  { countryCode: 'BF', name: 'Burkina Faso', region: 'Africa' },
  { countryCode: 'BI', name: 'Burundi', region: 'Africa' },
  { countryCode: 'CV', name: 'Cabo Verde', region: 'Africa' },
  { countryCode: 'KH', name: 'Cambodia', region: 'Asia' },
  { countryCode: 'CM', name: 'Cameroon', region: 'Africa' },
  { countryCode: 'CA', name: 'Canada', region: 'Americas' },
  { countryCode: 'KY', name: 'Cayman Islands', region: 'Americas' },
  { countryCode: 'CF', name: 'Central African Republic', region: 'Africa' },
  { countryCode: 'TD', name: 'Chad', region: 'Africa' },
  { countryCode: 'CL', name: 'Chile', region: 'Americas' },
  { countryCode: 'CN', name: 'China', region: 'Asia' },
  { countryCode: 'CX', name: 'Christmas Island', region: 'Oceania' },
  { countryCode: 'CC', name: 'Cocos (Keeling) Islands', region: 'Oceania' },
  { countryCode: 'CO', name: 'Colombia', region: 'Americas' },
  { countryCode: 'KM', name: 'Comoros', region: 'Africa' },
  { countryCode: 'CG', name: 'Congo', region: 'Africa' },
  { countryCode: 'CD', name: 'Congo (Democratic Republic of the)', region: 'Africa' },
  { countryCode: 'CK', name: 'Cook Islands', region: 'Oceania' },
  { countryCode: 'CR', name: 'Costa Rica', region: 'Americas' },
  { countryCode: 'CI', name: "Côte d'Ivoire", region: 'Africa' },
  { countryCode: 'HR', name: 'Croatia', region: 'Europe' },
  { countryCode: 'CU', name: 'Cuba', region: 'Americas' },
  { countryCode: 'CW', name: 'Curaçao', region: 'Americas' },
  { countryCode: 'CY', name: 'Cyprus', region: 'Asia' },
  { countryCode: 'CZ', name: 'Czechia', region: 'Europe' },
  { countryCode: 'DK', name: 'Denmark', region: 'Europe' },
  { countryCode: 'DJ', name: 'Djibouti', region: 'Africa' },
  { countryCode: 'DM', name: 'Dominica', region: 'Americas' },
  { countryCode: 'DO', name: 'Dominican Republic', region: 'Americas' },
  { countryCode: 'EC', name: 'Ecuador', region: 'Americas' },
  { countryCode: 'EG', name: 'Egypt', region: 'Africa' },
  { countryCode: 'SV', name: 'El Salvador', region: 'Americas' },
  { countryCode: 'GQ', name: 'Equatorial Guinea', region: 'Africa' },
  { countryCode: 'ER', name: 'Eritrea', region: 'Africa' },
  { countryCode: 'EE', name: 'Estonia', region: 'Europe' },
  { countryCode: 'ET', name: 'Ethiopia', region: 'Africa' },
  { countryCode: 'FK', name: 'Falkland Islands (Malvinas)', region: 'Africa' },
  { countryCode: 'FO', name: 'Faroe Islands', region: 'Americas' },
  { countryCode: 'FJ', name: 'Fiji', region: 'Europe' },
  { countryCode: 'FI', name: 'Finland', region: 'Oceania' },
  { countryCode: 'FR', name: 'France', region: 'Europe' },
  { countryCode: 'GF', name: 'French Guiana', region: 'Europe' },
  { countryCode: 'PF', name: 'French Polynesia', region: 'Americas' },
  { countryCode: 'TF', name: 'French Southern Territories', region: 'Oceania' },
  { countryCode: 'GA', name: 'Gabon', region: 'Africa' },
  { countryCode: 'GM', name: 'Gambia', region: 'Africa' },
  { countryCode: 'GE', name: 'Georgia', region: 'Africa' },
  { countryCode: 'DE', name: 'Germany', region: 'Asia' },
  { countryCode: 'GH', name: 'Ghana', region: 'Europe' },
  { countryCode: 'GI', name: 'Gibraltar', region: 'Africa' },
  { countryCode: 'GR', name: 'Greece', region: 'Europe' },
  { countryCode: 'GL', name: 'Greenland', region: 'Europe' },
  { countryCode: 'GD', name: 'Grenada', region: 'Americas' },
  { countryCode: 'GP', name: 'Guadeloupe', region: 'Americas' },
  { countryCode: 'GU', name: 'Guam', region: 'Americas' },
  { countryCode: 'GT', name: 'Guatemala', region: 'Oceania' },
  { countryCode: 'GG', name: 'Guernsey', region: 'Americas' },
  { countryCode: 'GN', name: 'Guinea', region: 'Europe' },
  { countryCode: 'GW', name: 'Guinea-Bissau', region: 'Africa' },
  { countryCode: 'GY', name: 'Guyana', region: 'Africa' },
  { countryCode: 'HT', name: 'Haiti', region: 'Americas' },
  { countryCode: 'HM', name: 'Heard Island and McDonald Islands', region: 'Americas' },
  { countryCode: 'VA', name: 'Holy See', region: 'Oceania' },
  { countryCode: 'HN', name: 'Honduras', region: 'Europe' },
  { countryCode: 'HK', name: 'Hong Kong', region: 'Americas' },
  { countryCode: 'HU', name: 'Hungary', region: 'Asia' },
  { countryCode: 'IS', name: 'Iceland', region: 'Europe' },
  { countryCode: 'IN', name: 'India', region: 'Europe' },
  { countryCode: 'ID', name: 'Indonesia', region: 'Asia' },
  { countryCode: 'IR', name: 'Iran (Islamic Republic of)', region: 'Asia' },
  { countryCode: 'IQ', name: 'Iraq', region: 'Asia' },
  { countryCode: 'IE', name: 'Ireland', region: 'Asia' },
  { countryCode: 'IM', name: 'Isle of Man', region: 'Europe' },
  { countryCode: 'IL', name: 'Israel', region: 'Europe' },
  { countryCode: 'IT', name: 'Italy', region: 'Asia' },
  { countryCode: 'JM', name: 'Jamaica', region: 'Europe' },
  { countryCode: 'JP', name: 'Japan', region: 'Americas' },
  { countryCode: 'JE', name: 'Jersey', region: 'Asia' },
  { countryCode: 'JO', name: 'Jordan', region: 'Europe' },
  { countryCode: 'KZ', name: 'Kazakhstan', region: 'Asia' },
  { countryCode: 'KE', name: 'Kenya', region: 'Asia' },
  { countryCode: 'KI', name: 'Kiribati', region: 'Africa' },
  { countryCode: 'KP', name: "Korea (Democratic People's Republic of)", region: 'Oceania' },
  { countryCode: 'KR', name: 'Korea (Republic of)', region: 'Asia' },
  { countryCode: 'KW', name: 'Kuwait', region: 'Asia' },
  { countryCode: 'KG', name: 'Kyrgyzstan', region: 'Asia' },
  { countryCode: 'LA', name: "Lao People's Democratic Republic", region: 'Asia' },
  { countryCode: 'LV', name: 'Latvia', region: 'Asia' },
  { countryCode: 'LB', name: 'Lebanon', region: 'Europe' },
  { countryCode: 'LS', name: 'Lesotho', region: 'Asia' },
  { countryCode: 'LR', name: 'Liberia', region: 'Africa' },
  { countryCode: 'LY', name: 'Libya', region: 'Africa' },
  { countryCode: 'LI', name: 'Liechtenstein', region: 'Africa' },
  { countryCode: 'LT', name: 'Lithuania', region: 'Europe' },
  { countryCode: 'LU', name: 'Luxembourg', region: 'Europe' },
  { countryCode: 'MO', name: 'Macao', region: 'Europe' },
  { countryCode: 'MK', name: 'North Macedonia', region: 'Asia' },
  { countryCode: 'MG', name: 'Madagascar', region: 'Africa' },
  { countryCode: 'MW', name: 'Malawi', region: 'Africa' },
  { countryCode: 'MY', name: 'Malaysia', region: 'Asia' },
  { countryCode: 'MV', name: 'Maldives', region: 'Asia' },
  { countryCode: 'ML', name: 'Mali', region: 'Africa' },
  { countryCode: 'MT', name: 'Malta', region: 'Europe' },
  { countryCode: 'MH', name: 'Marshall Islands', region: 'Oceania' },
  { countryCode: 'MQ', name: 'Martinique', region: 'Americas' },
  { countryCode: 'MR', name: 'Mauritania', region: 'Africa' },
  { countryCode: 'MU', name: 'Mauritius', region: 'Africa' },
  { countryCode: 'YT', name: 'Mayotte', region: 'Africa' },
  { countryCode: 'MX', name: 'Mexico', region: 'Americas' },
  { countryCode: 'FM', name: 'Micronesia (Federated States of)', region: 'Oceania' },
  { countryCode: 'MD', name: 'Moldova (Republic of)', region: 'Europe' },
  { countryCode: 'MC', name: 'Monaco', region: 'Europe' },
  { countryCode: 'MN', name: 'Mongolia', region: 'Asia' },
  { countryCode: 'ME', name: 'Montenegro', region: 'Europe' },
  { countryCode: 'MS', name: 'Montserrat', region: 'Americas' },
  { countryCode: 'MA', name: 'Morocco', region: 'Africa' },
  { countryCode: 'MZ', name: 'Mozambique', region: 'Africa' },
  { countryCode: 'MM', name: 'Myanmar', region: 'Asia' },
  { countryCode: 'NA', name: 'Namibia', region: 'Africa' },
  { countryCode: 'NR', name: 'Nauru', region: 'Oceania' },
  { countryCode: 'NP', name: 'Nepal', region: 'Asia' },
  { countryCode: 'NL', name: 'Netherlands', region: 'Europe' },
  { countryCode: 'NC', name: 'New Caledonia', region: 'Oceania' },
  { countryCode: 'NZ', name: 'New Zealand', region: 'Oceania' },
  { countryCode: 'NI', name: 'Nicaragua', region: 'Americas' },
  { countryCode: 'NE', name: 'Niger', region: 'Africa' },
  { countryCode: 'NG', name: 'Nigeria', region: 'Africa' },
  { countryCode: 'NU', name: 'Niue', region: 'Oceania' },
  { countryCode: 'NF', name: 'Norfolk Island', region: 'Oceania' },
  { countryCode: 'MP', name: 'Northern Mariana Islands', region: 'Europe' },
  { countryCode: 'NO', name: 'Norway', region: 'Oceania' },
  { countryCode: 'OM', name: 'Oman', region: 'Europe' },
  { countryCode: 'PK', name: 'Pakistan', region: 'Asia' },
  { countryCode: 'PW', name: 'Palau', region: 'Asia' },
  { countryCode: 'PS', name: 'Palestine, State of', region: 'Oceania' },
  { countryCode: 'PA', name: 'Panama', region: 'Asia' },
  { countryCode: 'PG', name: 'Papua New Guinea', region: 'Americas' },
  { countryCode: 'PY', name: 'Paraguay', region: 'Oceania' },
  { countryCode: 'PE', name: 'Peru', region: 'Americas' },
  { countryCode: 'PH', name: 'Philippines', region: 'Americas' },
  { countryCode: 'PN', name: 'Pitcairn', region: 'Asia' },
  { countryCode: 'PL', name: 'Poland', region: 'Oceania' },
  { countryCode: 'PT', name: 'Portugal', region: 'Europe' },
  { countryCode: 'PR', name: 'Puerto Rico', region: 'Europe' },
  { countryCode: 'QA', name: 'Qatar', region: 'Americas' },
  { countryCode: 'RE', name: 'Réunion', region: 'Asia' },
  { countryCode: 'RO', name: 'Romania', region: 'Africa' },
  { countryCode: 'RU', name: 'Russian Federation', region: 'Europe' },
  { countryCode: 'RW', name: 'Rwanda', region: 'Europe' },
  { countryCode: 'BL', name: 'Saint Barthélemy', region: 'Africa' },
  { countryCode: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', region: 'Americas' },
  { countryCode: 'KN', name: 'Saint Kitts and Nevis', region: 'Africa' },
  { countryCode: 'LC', name: 'Saint Lucia', region: 'Americas' },
  { countryCode: 'MF', name: 'Saint Martin (French part)', region: 'Americas' },
  { countryCode: 'PM', name: 'Saint Pierre and Miquelon', region: 'Americas' },
  { countryCode: 'VC', name: 'Saint Vincent and the Grenadines', region: 'Americas' },
  { countryCode: 'WS', name: 'Samoa', region: 'Americas' },
  { countryCode: 'SM', name: 'San Marino', region: 'Oceania' },
  { countryCode: 'ST', name: 'Sao Tome and Principe', region: 'Europe' },
  { countryCode: 'SA', name: 'Saudi Arabia', region: 'Africa' },
  { countryCode: 'SN', name: 'Senegal', region: 'Asia' },
  { countryCode: 'RS', name: 'Serbia', region: 'Africa' },
  { countryCode: 'SC', name: 'Seychelles', region: 'Europe' },
  { countryCode: 'SL', name: 'Sierra Leone', region: 'Africa' },
  { countryCode: 'SG', name: 'Singapore', region: 'Africa' },
  { countryCode: 'SX', name: 'Sint Maarten (Dutch part)', region: 'Asia' },
  { countryCode: 'SK', name: 'Slovakia', region: 'Americas' },
  { countryCode: 'SI', name: 'Slovenia', region: 'Europe' },
  { countryCode: 'SB', name: 'Solomon Islands', region: 'Europe' },
  { countryCode: 'SO', name: 'Somalia', region: 'Oceania' },
  { countryCode: 'ZA', name: 'South Africa', region: 'Africa' },
  { countryCode: 'GS', name: 'South Georgia and the South Sandwich Islands', region: 'Africa' },
  { countryCode: 'SS', name: 'South Sudan', region: 'Americas' },
  { countryCode: 'ES', name: 'Spain', region: 'Africa' },
  { countryCode: 'LK', name: 'Sri Lanka', region: 'Europe' },
  { countryCode: 'SD', name: 'Sudan', region: 'Asia' },
  { countryCode: 'SR', name: 'Suriname', region: 'Africa' },
  { countryCode: 'SJ', name: 'Svalbard and Jan Mayen', region: 'Americas' },
  { countryCode: 'SZ', name: 'Eswatini', region: 'Europe' },
  { countryCode: 'SE', name: 'Sweden', region: 'Europe' },
  { countryCode: 'CH', name: 'Switzerland', region: 'Europe' },
  { countryCode: 'SY', name: 'Syrian Arab Republic', region: 'Asia' },
  { countryCode: 'TW', name: 'Taiwan, Province of China[a]', region: 'Asia' },
  { countryCode: 'TJ', name: 'Tajikistan', region: 'Asia' },
  { countryCode: 'TZ', name: 'Tanzania, United Republic of', region: 'Africa' },
  { countryCode: 'TH', name: 'Thailand', region: 'Asia' },
  { countryCode: 'TL', name: 'Timor-Leste', region: 'Asia' },
  { countryCode: 'TG', name: 'Togo', region: 'Africa' },
  { countryCode: 'TK', name: 'Tokelau', region: 'Oceania' },
  { countryCode: 'TO', name: 'Tonga', region: 'Oceania' },
  { countryCode: 'TT', name: 'Trinidad and Tobago', region: 'Americas' },
  { countryCode: 'TN', name: 'Tunisia', region: 'Africa' },
  { countryCode: 'TR', name: 'Turkey', region: 'Asia' },
  { countryCode: 'TM', name: 'Turkmenistan', region: 'Asia' },
  { countryCode: 'TC', name: 'Turks and Caicos Islands', region: 'Americas' },
  { countryCode: 'TV', name: 'Tuvalu', region: 'Oceania' },
  { countryCode: 'UG', name: 'Uganda', region: 'Africa' },
  { countryCode: 'UA', name: 'Ukraine', region: 'Europe' },
  { countryCode: 'AE', name: 'United Arab Emirates', region: 'Asia' },
  {
    countryCode: 'GB',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    region: 'Europe',
  },
  { countryCode: 'US', name: 'United States of America', region: 'Americas' },
  { countryCode: 'UM', name: 'United States Minor Outlying Islands', region: 'Oceania' },
  { countryCode: 'UY', name: 'Uruguay', region: 'Americas' },
  { countryCode: 'UZ', name: 'Uzbekistan', region: 'Asia' },
  { countryCode: 'VU', name: 'Vanuatu', region: 'Oceania' },
  { countryCode: 'VE', name: 'Venezuela (Bolivarian Republic of)', region: 'Americas' },
  { countryCode: 'VN', name: 'Viet Nam', region: 'Asia' },
  { countryCode: 'VG', name: 'Virgin Islands (British)', region: 'Americas' },
  { countryCode: 'VI', name: 'Virgin Islands (U.S.)', region: 'Americas' },
  { countryCode: 'WF', name: 'Wallis and Futuna', region: 'Oceania' },
  { countryCode: 'EH', name: 'Western Sahara', region: 'Africa' },
  { countryCode: 'YE', name: 'Yemen', region: 'Asia' },
  { countryCode: 'ZM', name: 'Zambia', region: 'Africa' },
  { countryCode: 'ZW', name: 'Zimbabwe', region: 'Africa' },
];

list.countryCodes = [];
list.names = [];

const countryCodeLookup = Object.create(null);
const nameLookup = Object.create(null);

list.name = function name(countryCode) {
  return nameLookup[countryCode.toUpperCase()];
};
list.countryCode = function countryCode(name) {
  return countryCodeLookup[name.toLowerCase()];
};

let country;
for (let i = 0, len = list.length; i < len; i++) {
  country = list[i];
  list.countryCodes.push(country.countryCode);
  list.names.push(country.name);
  countryCodeLookup[country.name.toLowerCase()] = country;
  nameLookup[country.countryCode] = country;
}

export default list;
